name: "Install uv"
description: "Install Python and uv"

inputs:
  PYTHON_VERSION:
    required: true
    description: "The Python version to use"

runs:
  using: "composite"
  steps:
    - name: Use given Python version
      shell: bash
      run: |
        echo "PYTHON_VERSION=${{ inputs.PYTHON_VERSION }}" >> $GITHUB_ENV

    - name: Install uv with Python ${{ env.PYTHON_VERSION }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
