name: "Testing"
description: "Run unit tests"

inputs:
  PACKAGE:
    required: true
    description: "The UV package to run tests for"
  PYTHON_VERSION:
    required: true
    description: "The Python version to run the test on"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install-uv
      with:
        PYTHON_VERSION: ${{ inputs.python_version }}

    - name: Pytest
      shell: bash
      run: |
        uv run --package evo-data-converters-${{ inputs.package }} pytest packages/${{ inputs.package }}/tests/