name: Build and publish package

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-uv

      - name: Pytest
        shell: bash
        run: |
          export UV_INDEX_ARTIFACTORY_USERNAME=${{ vars.EVO_ARTIFACTORY_USER }}
          export UV_INDEX_ARTIFACTORY_PASSWORD=${{ secrets.EVO_ARTIFACTORY_TOKEN }}
          uv run pytest tests/

  build-package:
    name: Build package
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-uv

      - name: Build
        shell: bash
        run: |
          export UV_INDEX_ARTIFACTORY_USERNAME=${{ vars.EVO_ARTIFACTORY_USER }}
          export UV_INDEX_ARTIFACTORY_PASSWORD=${{ secrets.EVO_ARTIFACTORY_TOKEN }}
          uv build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist

      - name: Publish to Artifactory
        shell: bash
        run: |
          export UV_INDEX_ARTIFACTORY_USERNAME=${{ vars.EVO_ARTIFACTORY_USER }}
          export UV_INDEX_ARTIFACTORY_PASSWORD=${{ secrets.EVO_ARTIFACTORY_TOKEN }}
          uv publish --index artifactory
