name: Tests and Linting

on:
  pull_request:

jobs:
  run-linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        shell: bash
        run: |
          PY_VER=$(cat .python-version)
          echo "PYTHON_VERSION=$PY_VER" >> $GITHUB_ENV

      - name: Install uv with Python ${{ env.PYTHON_VERSION }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Ruff check and format
        shell: bash
        run: |
          uv run --only-dev ruff check
          uv run --only-dev ruff format --check

  run-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        shell: bash
        run: |
          PY_VER=$(cat .python-version)
          echo "PYTHON_VERSION=$PY_VER" >> $GITHUB_ENV

      - name: Install uv with Python ${{ env.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Pytest
        shell: bash
        run: |
          export UV_INDEX_ARTIFACTORY_USERNAME=${{ vars.EVO_ARTIFACTORY_USER }}
          export UV_INDEX_ARTIFACTORY_PASSWORD=${{ secrets.EVO_ARTIFACTORY_TOKEN }}
          uv run pytest tests/

  build-dev:
    needs: [run-linting, run-tests]
    name: Build dev package
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run: |
          VERSION=$(grep version pyproject.toml -m 1 | cut -d'"' -f2)
          sed -i "s/^version.*=.*$/version = \"$VERSION.${{ github.run_id }}\"/" pyproject.toml
          uv build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
