name: Tests and Linting

on:
  pull_request:

permissions:
  contents: read

jobs:
  run-linting:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linting

  run-tests:
    uses: ./.github/workflows/run-all-tests.yaml
